name: chef_challenge_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  auto_route: ^10.1.2
  blurrycontainer: ^2.1.0
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.2.0
  flutter_svg_provider: ^1.0.7
  freezed_annotation: ^3.1.0
  google_fonts: ^6.3.0
  html: ^0.15.6
  meta: ^1.15.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  auto_route_generator: ^10.2.3
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  assets: 
    - .env
    - assets/icons/
